name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0       # Fetch full history to get all files properly

      - name: Docker version
        run: docker --version

      - name: Docker Compose version
        run: docker compose version

      - name: Show current directory
        run: pwd

      - name: List all project files recursively
        run: ls -R

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: List frontend folder contents   # Debug: make sure files exist
        run: ls -l frontend/

      - name: Build Docker Compose images
        run: docker compose -f docker-compose.yml build
